
project_id = "yhorkfzqcsejrmyrrqpb"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[db.pooler]
enabled = false
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"          # ✅ Fixed casing ("IPv4", not "ipv4")
max_header_length = 4096

[studio]
enabled = true
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
template = { }

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[functions.send-auth-email]
verify_jwt = false

[edge_runtime]
enabled = true

[analytics]
enabled = false
backend = "postgres"
