const jobTypes = ["Full-Time","Part-Time","Contract","Internship","Temporary","Remote","Freelance"];
const getRandomType = () => jobTypes[Math.floor(Math.random() * jobTypes.length)];

export const fakeJobs = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechNova Solutions",
    location: "London, UK",
    country: "UK",
    type: getRandomType(),
    description: "Build responsive web apps using React and TypeScript.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_1",
    application_email: "hr@technova.com",
    application_url: null,
    benefits: "Health insurance, Paid vacation",
    requirements: "React, TypeScript, HTML, CSS",
    salary_range: "50k-70k",
    featured: false,
    expires_at: null,
  },
  {
    id: "2",
    title: "Backend Engineer",
    company: "DataForge Inc.",
    location: "New York, USA",
    country: "USA",
    type: getRandomType(),
    description: "Design scalable backend services with Node.js and MongoDB.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_2",
    application_email: "jobs@dataforge.com",
    application_url: null,
    benefits: "401k, Remote option",
    requirements: "Node.js, Express, MongoDB",
    salary_range: "80k-110k",
    featured: true,
    expires_at: null,
  },
  {
    id: "3",
    title: "UX Designer",
    company: "Creative Minds",
    location: "Manchester, UK",
    country: "UK",
    type: getRandomType(),
    description: "Design user-centric interfaces and improve UX across web platforms.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_3",
    application_email: "design@creativeminds.co.uk",
    application_url: null,
    benefits: "Flexible hours, Health insurance",
    requirements: "Figma, Adobe XD, Wireframing",
    salary_range: "40k-60k",
    featured: false,
    expires_at: null,
  },
  {
    id: "4",
    title: "Data Scientist",
    company: "Analytics Hub",
    location: "San Francisco, USA",
    country: "USA",
    type: getRandomType(),
    description: "Analyze datasets to extract insights and develop predictive models.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_4",
    application_email: "careers@analyticshub.com",
    application_url: null,
    benefits: "Stock options, Remote work",
    requirements: "Python, R, SQL, Machine Learning",
    salary_range: "100k-140k",
    featured: true,
    expires_at: null,
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "CloudWorks",
    location: "Bristol, UK",
    country: "UK",
    type: getRandomType(),
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_5",
    application_email: "hr@cloudworks.uk",
    application_url: null,
    benefits: "Health insurance, Flexible schedule",
    requirements: "AWS, Docker, Kubernetes",
    salary_range: "70k-95k",
    featured: false,
    expires_at: null,
  },
  {
    id: "6",
    title: "Product Manager",
    company: "NextGen Tech",
    location: "Chicago, USA",
    country: "USA",
    type: getRandomType(),
    description: "Lead teams to define product vision and roadmap.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_6",
    application_email: "jobs@nextgentech.com",
    application_url: null,
    benefits: "Health benefits, Paid vacation",
    requirements: "Product Management, Agile, Communication",
    salary_range: "90k-120k",
    featured: true,
    expires_at: null,
  },
  {
    id: "7",
    title: "Fullstack Developer",
    company: "InnovateX",
    location: "Edinburgh, UK",
    country: "UK",
    type: getRandomType(),
    description: "Develop end-to-end web applications using React and Node.js.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_7",
    application_email: "dev@innovatex.co.uk",
    application_url: null,
    benefits: "Flexible schedule, Health insurance",
    requirements: "React, Node.js, PostgreSQL",
    salary_range: "60k-85k",
    featured: false,
    expires_at: null,
  },
  {
    id: "8",
    title: "Mobile App Developer",
    company: "AppSphere",
    location: "Los Angeles, USA",
    country: "USA",
    type: getRandomType(),
    description: "Build and maintain iOS and Android apps with Flutter.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_8",
    application_email: "careers@appsphere.com",
    application_url: null,
    benefits: "Remote option, Health benefits",
    requirements: "Flutter, Swift, Kotlin",
    salary_range: "70k-95k",
    featured: false,
    expires_at: null,
  },
  {
    id: "9",
    title: "Marketing Specialist",
    company: "Brandify",
    location: "London, UK",
    country: "UK",
    type: getRandomType(),
    description: "Develop marketing campaigns to drive brand awareness.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_9",
    application_email: "marketing@brandify.co.uk",
    application_url: null,
    benefits: "Flexible hours, Bonus",
    requirements: "SEO, Content Marketing, Analytics",
    salary_range: "45k-65k",
    featured: false,
    expires_at: null,
  },
  {
    id: "10",
    title: "AI Researcher",
    company: "DeepThink Labs",
    location: "Boston, USA",
    country: "USA",
    type: getRandomType(),
    description: "Research and implement machine learning models.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_10",
    application_email: "research@deepthinklabs.com",
    application_url: null,
    benefits: "Stock options, Health insurance",
    requirements: "Python, TensorFlow, PyTorch",
    salary_range: "110k-150k",
    featured: true,
    expires_at: null,
  },
  {
    id: "11",
    title: "Graphic Designer",
    company: "PixelWorks",
    location: "Manchester, UK",
    country: "UK",
    type: getRandomType(),
    description: "Create visual designs for web and mobile apps.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_11",
    application_email: "design@pixelworks.co.uk",
    application_url: null,
    benefits: "Health insurance, Flexible hours",
    requirements: "Photoshop, Illustrator, Figma",
    salary_range: "35k-50k",
    featured: false,
    expires_at: null,
  },
  {
    id: "12",
    title: "QA Engineer",
    company: "TestLab Inc.",
    location: "New York, USA",
    country: "USA",
    type: getRandomType(),
    description: "Test software applications and ensure quality standards.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_12",
    application_email: "qa@testlab.com",
    application_url: null,
    benefits: "Remote work, Paid vacation",
    requirements: "Manual & Automated Testing, Selenium",
    salary_range: "60k-80k",
    featured: false,
    expires_at: null,
  },
  {
    id: "13",
    title: "Cloud Architect",
    company: "Skyline Cloud",
    location: "Bristol, UK",
    country: "UK",
    type: getRandomType(),
    description: "Design cloud infrastructure and scalable solutions.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_13",
    application_email: "cloud@skyline.co.uk",
    application_url: null,
    benefits: "Health insurance, Stock options",
    requirements: "AWS, Azure, Kubernetes",
    salary_range: "90k-120k",
    featured: true,
    expires_at: null,
  },
  {
    id: "14",
    title: "Content Writer",
    company: "WriteRight",
    location: "Los Angeles, USA",
    country: "USA",
    type: getRandomType(),
    description: "Create engaging content for blogs, websites, and social media.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_14",
    application_email: "jobs@writeright.com",
    application_url: null,
    benefits: "Remote option, Flexible hours",
    requirements: "SEO, Blogging, Copywriting",
    salary_range: "40k-55k",
    featured: false,
    expires_at: null,
  },
  {
    id: "15",
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    location: "Edinburgh, UK",
    country: "UK",
    type: getRandomType(),
    description: "Monitor and protect company networks from cyber threats.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_15",
    application_email: "security@securenet.co.uk",
    application_url: null,
    benefits: "Health insurance, Flexible schedule",
    requirements: "Network Security, Penetration Testing",
    salary_range: "70k-95k",
    featured: false,
    expires_at: null,
  },
  {
    id: "16",
    title: "Business Analyst",
    company: "Insight Corp",
    location: "Chicago, USA",
    country: "USA",
    type: getRandomType(),
    description: "Analyze business processes and recommend solutions.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_16",
    application_email: "careers@insightcorp.com",
    application_url: null,
    benefits: "Health insurance, Paid vacation",
    requirements: "SQL, Excel, Power BI",
    salary_range: "65k-90k",
    featured: false,
    expires_at: null,
  },
  {
    id: "17",
    title: "SEO Specialist",
    company: "MarketBoost",
    location: "London, UK",
    country: "UK",
    type: getRandomType(),
    description: "Improve website ranking and optimize SEO campaigns.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_17",
    application_email: "seo@marketboost.co.uk",
    application_url: null,
    benefits: "Flexible hours, Remote option",
    requirements: "SEO, Google Analytics, SEM",
    salary_range: "45k-60k",
    featured: false,
    expires_at: null,
  },
  {
    id: "18",
    title: "UI Developer",
    company: "InterfaceX",
    location: "San Francisco, USA",
    country: "USA",
    type: getRandomType(),
    description: "Develop visually appealing and responsive web interfaces.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_18",
    application_email: "ui@interfacex.com",
    application_url: null,
    benefits: "Remote work, Health benefits",
    requirements: "HTML, CSS, JavaScript, React",
    salary_range: "70k-95k",
    featured: false,
    expires_at: null,
  },
  {
    id: "19",
    title: "Systems Administrator",
    company: "NetSecure",
    location: "Bristol, UK",
    country: "UK",
    type: getRandomType(),
    description: "Maintain servers, networks, and ensure system stability.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_19",
    application_email: "sysadmin@netsecure.co.uk",
    application_url: null,
    benefits: "Health insurance, Paid vacation",
    requirements: "Linux, Windows Server, Networking",
    salary_range: "60k-85k",
    featured: false,
    expires_at: null,
  },
  {
    id: "20",
    title: "AI Product Manager",
    company: "BrainTech",
    location: "Boston, USA",
    country: "USA",
    type: getRandomType(),
    description: "Manage AI product development and roadmap execution.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    user_id: "user_20",
    application_email: "pm@braintech.com",
    application_url: null,
    benefits: "Stock options, Remote work",
    requirements: "AI/ML knowledge, Product Management, Agile",
    salary_range: "100k-130k",
    featured: true,
    expires_at: null,
  },
];
